name: Sign Firefox Android XPI (from build ZIP)

concurrency:
  group: xpi-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  push:
    branches: [ defmikekoh ]
  workflow_dispatch: {}

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install tools (web-ext, jq, unzip)
        run: |
          npm i -g web-ext
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Install deps and build
        run: |
          npm ci
          npm run build

      - name: Locate build ZIP
        id: findzip
        run: |
          ls -1 web-ext-artifacts/*.zip | sort | tail -n 1 > /tmp/zip_path
          ZIP=$(cat /tmp/zip_path)
          if [ ! -s /tmp/zip_path ]; then
            echo "No ZIP found in web-ext-artifacts/" >&2
            exit 1
          fi
          echo "zip=$ZIP" >> $GITHUB_OUTPUT
          echo "Found ZIP: $ZIP"

      - name: Unzip to source dir for signing
        id: unzip
        run: |
          rm -rf build_src
          mkdir -p build_src
          unzip -q "${{ steps.findzip.outputs.zip }}" -d build_src

          # Find the folder that actually contains manifest.json
          MF=$(find build_src -maxdepth 3 -type f -name manifest.json | head -n 1 || true)
          if [ -z "$MF" ]; then
            echo "manifest.json not found inside the ZIP" >&2
            exit 1
          fi
          SRC_DIR=$(dirname "$MF")
          echo "src_dir=$SRC_DIR" >> $GITHUB_OUTPUT
          echo "Using source dir: $SRC_DIR"

      - name: Ensure Gecko ID exists
        run: |
          ID=$(jq -r '.browser_specific_settings.gecko.id // .applications.gecko.id // empty' "${{ steps.unzip.outputs.src_dir }}/manifest.json")
          if [ -z "$ID" ]; then
            echo "ERROR: manifest.json must include browser_specific_settings.gecko.id (or applications.gecko.id)." >&2
            exit 1
          fi
          echo "Gecko ID: $ID"

      # Optional: bump version inside the unzipped manifest so AMO accepts each submission
      # Remove this step if your build already changes version per-commit.
      - name: Bump version (4th = run number)
        run: |
          MF="${{ steps.unzip.outputs.src_dir }}/manifest.json"

          # Grab first 3 numeric components from manifest
          base=$(jq -r .version "$MF" | cut -d. -f1-3)
          if ! echo "$base" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "ERROR: manifest.json version must start with three numeric components" >&2
            exit 1
          fi

          # Use GitHub Actions run number as the 4th component
          rn="${GITHUB_RUN_NUMBER}"

          new_version="${base}.${rn}"
          jq --arg v "$new_version" '.version = $v' "$MF" > "$MF.tmp" && mv "$MF.tmp" "$MF"
          echo "New version: $(jq -r .version "$MF")"

      - name: Capture version for artifact/release names
        id: ver
        run: |
          MF="${{ steps.unzip.outputs.src_dir }}/manifest.json"
          echo "v=$(jq -r .version "$MF")" >> $GITHUB_OUTPUT
          echo "Version: $(jq -r .version "$MF")"

      - name: Sign on AMO (unlisted)
        env:
          AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
          AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
        run: |
          mkdir -p signed
          web-ext sign \
            --channel=unlisted \
            --source-dir "${{ steps.unzip.outputs.src_dir }}" \
            --artifacts-dir ./signed \
            --api-key "$AMO_JWT_ISSUER" \
            --api-secret "$AMO_JWT_SECRET" \
            --timeout 60000

      - name: Upload signed XPI
        uses: actions/upload-artifact@v4
        with:
          name: signed-xpi-${{ steps.ver.outputs.v }}
          path: signed/*.xpi

      # Draft release on every push for a direct .xpi link
      - name: Create/Update draft "latest" release (every push)
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: android-test-latest
          name: Android test (latest) ${{ steps.ver.outputs.v }}
          body: |
            Draft build for Android testing.
            Version: ${{ steps.ver.outputs.v }}
            Commit: ${{ github.sha }}
          draft: true
          prerelease: true
          files: signed/*.xpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print direct link and QR to latest draft .xpi
        if: github.event_name == 'push'
        run: |
          echo "Fetching latest release download URL..."
          API_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/android-test-latest"
          DOWNLOAD_URL=$(curl -sL "$API_URL" | jq -r '.assets[0].browser_download_url')
          if [ "$DOWNLOAD_URL" = "null" ] || [ -z "$DOWNLOAD_URL" ]; then
            echo "No asset found for latest draft release."
            exit 1
          fi
          echo "Direct download URL: $DOWNLOAD_URL"
          echo
          echo "QR code for mobile download:"
          curl -s "https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${DOWNLOAD_URL}" --output qrcode.png
          # Display as base64 in logs so it's clickable
          echo "data:image/png;base64,$(base64 -w0 qrcode.png)"

      # Optional: attach to a Release for easy tap-download on Android
      - name: Create GitHub Release (manual runs only)
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: android-test-${{ steps.ver.outputs.v }}
          name: Android test build ${{ steps.ver.outputs.v }}
          body: "Signed XPI for Android testing (unlisted)."
          files: signed/*.xpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
